const constants = {
  ADD_POINT: 'ADD_POINT',
  MOVE_POINT: 'MOVE_POINT',
  DELETE_POINT: 'DELETE_POINT',
  UPDATE_INPUT_VALUE: 'UPDATE_INPUT_VALUE',
  UPDATE_COORDINATES: 'UPDATE_COORDINATES',
  UPDATE_MAP_CENTER: 'UPDATE_MAP_CENTER',
};

export default constants;
